# Generated by Django 2.2 on 2019-08-04 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programasradiales',
            name='radios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Radio'),
        ),
    ]
